# Exercises:
* Questions: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [1]:
import torch

In [2]:
#2. Create a random tensor with shape (7, 7)

x = torch.rand(7,7)
print(x)
print(x.shape)

tensor([[0.2545, 0.0760, 0.5886, 0.9227, 0.0588, 0.4140, 0.1438],
        [0.9131, 0.9783, 0.1459, 0.1782, 0.0827, 0.1932, 0.3367],
        [0.3056, 0.3404, 0.8762, 0.8337, 0.9914, 0.2864, 0.8471],
        [0.6549, 0.0045, 0.4441, 0.0971, 0.1744, 0.0445, 0.5051],
        [0.8873, 0.0465, 0.5653, 0.2958, 0.2584, 0.8581, 0.6487],
        [0.7770, 0.1095, 0.3998, 0.7355, 0.6487, 0.7494, 0.7074],
        [0.8826, 0.2194, 0.3223, 0.6034, 0.4245, 0.8586, 0.9939]])
torch.Size([7, 7])


In [3]:
# 3. 
# Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

y = torch.rand(1,7).T
result = torch.matmul(x,y)
print(result)
print(result.shape)

tensor([[1.4707],
        [1.1894],
        [2.6794],
        [1.1738],
        [1.6989],
        [2.0324],
        [2.0003]])
torch.Size([7, 1])


In [4]:
#4. Set the random seed to 0 and do exercises 2 & 3 over again.
MANUAL_SEED = 0
torch.manual_seed(MANUAL_SEED)

x = torch.rand(7,7)
y = torch.rand(1,7).T
result = torch.matmul(x, y)
print(result)
print(result.shape)

tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])
torch.Size([7, 1])


In [5]:
# 5.
# Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? 
# (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

torch.cuda.manual_seed(MANUAL_SEED)

In [6]:
# 6. 
# Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). 
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

torch.manual_seed(1234)
print('Is cuda available? ', torch.cuda.is_available())
x = torch.rand(2, 3).to('cuda')
y = torch.rand(2, 3).to('cuda')

Is cuda available?  True


In [10]:
#7. 
# Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
result = torch.matmul(x, y.T)
print(result)
print(result.shape)

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')
torch.Size([2, 2])


In [ ]:
# 8.
# Find the maximum and minimum values of the output of 7.
max = torch.max(result)
min = torch.min(result)

print('Max: ', max)
print('Min:', min)

Max:  tensor(0.5617, device='cuda:0')
Min: tensor(0.3647, device='cuda:0')


In [15]:
# 9.
# Find the maximum and minimum index values of the output of 7.
maxIdx = torch.argmax(result)
minIdx = torch.argmin(result)

print('MaxIdx: ', maxIdx)
print('MinIdx: ', minIdx)

MaxIdx:  tensor(3, device='cuda:0')
MinIdx:  tensor(0, device='cuda:0')


In [16]:
# 10.
# Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). 
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

torch.manual_seed(7)
x = torch.rand(1,1,1,10)
print('Original Tensor')
print(x, x.shape)

y = x.squeeze()
print('Squeeze Tensor')
print(y, y.shape)

Original Tensor
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
Squeeze Tensor
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
