# Fundamentals

In [2]:
import torch
import numpy as np

## Introduction to Tensors

In [3]:
# Scalar
scalar = torch.tensor(7)
print('Dimension of a scalar: ', scalar.ndim)
print('Return scalar tensor into python int: ', scalar.item())

Dimension of a scalar:  0
Return scalar tensor into python int:  7


In [4]:
# Vector
vector = torch.tensor([6, 7])
print('Dimension of a vector: ', vector.ndim)
print('Shape of a vector', vector.shape)

Dimension of a vector:  1
Shape of a vector torch.Size([2])


In [5]:
# Matrix
matrix = torch.tensor([ [2,3,5], [4,5,6] ])
print('The dimension of a matrix: ', matrix.ndim)
print('The shape of a matrix', matrix.shape)
print('The first element of the matrix:', matrix[0][0].item())

The dimension of a matrix:  2
The shape of a matrix torch.Size([2, 3])
The first element of the matrix: 2


In [6]:
# Tensor
TENSOR = torch.tensor( [
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])

print('The dimension of the tensor: ', TENSOR.ndim)
print('The shape of the tensor: ', TENSOR.shape)
print('The first element of the tensor: ', TENSOR[0][0][0].item())

The dimension of the tensor:  3
The shape of the tensor:  torch.Size([2, 2, 3])
The first element of the tensor:  1


## Random Tensors

In [7]:
random_tensor = torch.rand(2,3,2)
print(f'The random tensor:\n{random_tensor}')


The random tensor:
tensor([[[0.1240, 0.0732],
         [0.3333, 0.0550],
         [0.6201, 0.0202]],

        [[0.1820, 0.5193],
         [0.2772, 0.5824],
         [0.5979, 0.6749]]])


## Zeros and ones

In [8]:
zeros = torch.zeros(3,4)
print(f'The zero elements:\n{zeros}')
print(f'The data type: {zeros.dtype}')

The zero elements:
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
The data type: torch.float32


In [9]:
ones = torch.ones(3,4)
print(f'The one elements:\n{ones}')
print(f'The data type: {ones.dtype}')

The one elements:
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
The data type: torch.float32


## Creating a range of tensors and tensors-like

In [10]:
# Arange
range = torch.arange(0, 10, 1)
print(range)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [11]:
# Creating tensors like
ten_zeros = torch.zeros_like(range)
ten_ones = torch.ones_like(range)
ten_rand = torch.rand_like(range.to(torch.float64)) # Require to cast to the same data type first
print(f'ten_zeros which share the same shape as range: {ten_zeros}')
print(f'ten_ones which share the same shape as range: {ten_ones}')
print(f'random tensor which share the same shape as range: {ten_rand}')

ten_zeros which share the same shape as range: tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
ten_ones which share the same shape as range: tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])
random tensor which share the same shape as range: tensor([0.3543, 0.5758, 0.3736, 0.0349, 0.0379, 0.9884, 0.5678, 0.0663, 0.7135,
        0.9278], dtype=torch.float64)


## Tensor Datatype

In [12]:
float_16_tensor = torch.tensor(
    [2,3,4,5],
    device='cpu',
    requires_grad=False,
    dtype=torch.float16
)

print(float_16_tensor)

tensor([2., 3., 4., 5.], dtype=torch.float16)


In [13]:
float_32_tensor = float_16_tensor.to(torch.float32)
print(float_32_tensor)
print(float_32_tensor.dtype)

tensor([2., 3., 4., 5.])
torch.float32


## Getting information from Tensors

In [14]:
TENSOR = torch.rand(2,3,3)
# Get dtype
print('The data type: ', TENSOR.dtype)
print('The data shape: ', TENSOR.shape)
print('The device where the data is on: ', TENSOR.device)


The data type:  torch.float32
The data shape:  torch.Size([2, 3, 3])
The device where the data is on:  cpu


## Manipulating Tensors

In [15]:
# Addition / Multiplication with scalar
tensor = torch.tensor([1,2,3])
print('tensor + 10 = ', tensor + 10)
print('tensor * 10 = ', tensor * 10)

tensor + 10 =  tensor([11, 12, 13])
tensor * 10 =  tensor([10, 20, 30])


In [16]:
# Matrix Multiplcation
tensorA = torch.tensor([1,2,3])
tensorB = torch.tensor([2,2,2])
print('torch.matmul(tensorA, tensorB) = ', torch.matmul(tensorA, tensorB))


torch.matmul(tensorA, tensorB) =  tensor(12)


## Tensor Aggregation (Mean, Max, Sum)

In [17]:
x = torch.arange(0, 10, 1)
max = torch.max(x)
maxIdx = torch.argmax(x)
mean = torch.mean(x.to(torch.float32))
sum = torch.sum(x)

print('Original Tensor: ', x)
print('Max: ', max)
print('Max Idx:', maxIdx)
print('Mean: ', mean)
print('Sum:', sum)

Original Tensor:  tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Max:  tensor(9)
Max Idx: tensor(9)
Mean:  tensor(4.5000)
Sum: tensor(45)


## Reshape, Stack, Squeeze and Unsqueeze

In [18]:
# Reshape / stack 
x = torch.arange(0., 9.)

reshape = x.reshape(3,3)
stack1 = torch.stack([x, x], dim=0)
stack2 = torch.stack([x, x], dim=1)

print('Original:\n', x)
print('Reshape to 3x3:\n', reshape)
print('Stack1:\n', stack1)
print('Stack2:\n', stack2)

Original:
 tensor([0., 1., 2., 3., 4., 5., 6., 7., 8.])
Reshape to 3x3:
 tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])
Stack1:
 tensor([[0., 1., 2., 3., 4., 5., 6., 7., 8.],
        [0., 1., 2., 3., 4., 5., 6., 7., 8.]])
Stack2:
 tensor([[0., 0.],
        [1., 1.],
        [2., 2.],
        [3., 3.],
        [4., 4.],
        [5., 5.],
        [6., 6.],
        [7., 7.],
        [8., 8.]])


In [19]:
# Squeeze / Unsqueeze
x = torch.zeros(1,2,2,1)

print('Original shape of x: ', x.shape)
print('Squeezed x shape: ', torch.squeeze(x).shape)
print('Unsqueezed x shape: ', torch.unsqueeze(x, dim=2).shape)

Original shape of x:  torch.Size([1, 2, 2, 1])
Squeezed x shape:  torch.Size([2, 2])
Unsqueezed x shape:  torch.Size([1, 2, 1, 2, 1])


In [20]:
# Permute

x = torch.rand(3, 64, 64)
permuted = torch.permute(x, (1,2,0))
print("Original x's shape: ", x.shape)
print("Permuted x's shape: ", permuted.shape)


Original x's shape:  torch.Size([3, 64, 64])
Permuted x's shape:  torch.Size([64, 64, 3])


## Torch Tensor & Numpy Array

In [21]:
# Numpy Array -> Torch Tensor
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)

# Torch Tensor -> Numpy Array
convArray = torch.Tensor.numpy(tensor)

print('Converted from numpy to tensor: ', tensor)
print('Converted from tensor to numpy: ', convArray)



Converted from numpy to tensor:  tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)
Converted from tensor to numpy:  [1. 2. 3. 4. 5. 6. 7.]


## Seed

In [22]:
MANUAL_SEED = 42
torch.manual_seed(MANUAL_SEED)
print(torch.rand(2,2))

tensor([[0.8823, 0.9150],
        [0.3829, 0.9593]])


## Device / CUDA

In [23]:
!nvidia-smi

Tue Apr 14 06:02:27 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   36C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [24]:
# Check if cuda is available
print(torch.cuda.is_available())

True


In [25]:
# Device-agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [30]:
# Putting tensors (and models) on the GPU

# Method 1
tensor = torch.tensor([1,2,3], device=device)
print('Method 1:', tensor.device)

# Method 2 - Transfer from cpu to gpu
tensor = torch.tensor([1,2,3])
print('Method 2 (Initial):', tensor.device)
tensor_on_gpu = tensor.to(device)
print('Method 2 (After moving from cpu to gpu):', tensor_on_gpu.device)

Method 1: cuda:0
Method 2 (Initial): cpu
Method 2 (After moving from cpu to gpu): cuda:0
